packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react19:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "@types/react": "19.0.3"
    "@types/react-dom": "19.0.2"
  tailwindcss:
    "tailwindcss": "^3.4.17"
    "postcss": "^8.4.47"
    "autoprefixer": "^10.4.20"
  typescript5:
    "typescript": "^5.7.3"
  zod3:
    "zod": "^3.24.1"
  lucide-react:
    "lucide-react": "0.473.0"
  fumadocs:
    "fumadocs-core": "^14.7.4"
    "fumadocs-docgen": "^1.3.4"
    "fumadocs-mdx": "^11.3.1"
    "fumadocs-ui": "^14.7.4"
