packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react19:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "@types/react": "19.0.3"
    "@types/react-dom": "19.0.2"
  tailwindcss:
    "tailwindcss": "^4.0.0"
    "postcss": "^8.4.47"
    "@tailwindcss/postcss": "^4.0.0"
  typescript5:
    "typescript": "^5.7.3"
  zod3:
    "zod": "^3.24.1"
  lucide-react:
    "lucide-react": "0.474.0"
  fumadocs:
    "fumadocs-core": "^15.0.0"
    "fumadocs-docgen": "^1.3.5"
    "fumadocs-mdx": "^11.3.2"
    "fumadocs-ui": "^15.0.0"
