packages:
  - "apps/*"
  - "packages/*"
# Use npx taze -r to update all packages
catalogs:
  react19:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "19.0.3"
    "@types/react-dom": "19.0.2"
  tailwindcss:
    "tailwindcss": "^4.1.3"
    "postcss": "^8.5.3"
    "@tailwindcss/postcss": "^4.1.3"
  typescript5:
    "typescript": "^5.8.3"
  zod3:
    "zod": "^3.24.2"
  lucide-react:
    "lucide-react": "0.474.0"
  fumadocs:
    "fumadocs-core": "^15.2.4"
    "fumadocs-docgen": "^1.3.8"
    "fumadocs-mdx": "^11.5.8"
    "fumadocs-ui": "^15.2.4"
